### PR TITLE
changes for partial search collection indentifier

### PR DESCRIPTION
**Pull request by smntb**
Change search functionality from exact match to partial match on Collection Identifier field.

### CODE REVIEW

**Comment by cvonkleist** [comment]
Thanks for this improvement, @smntb!

**Comment by chrisprom** [comment]
Just to ask, will this change still match an exact string search, for example if I search for a muli-part identifier such as 12/3/14 where 12 and 3 come from the classification, and 14 from the Collection Identifier Field?  That features is important to many users.

**Comment by bertramlyons** [comment]
@chrisprom I tested against your question above, and the search adjustments still return such a string (I tested the exact question you asked above -- classification 12 -> classification 3 -> collection 14. Search criteria: 12/3/14. The collection in question was returned, on front end and back end.

**Comment by chrisprom** [comment]
Thanks Bert.  We much appreciate this enhancement.

**Pull request merged**
